### ISSUE TITLE
Phase 1 - ambitious

### ISSUE THREAD

**Issue by w1zeman1p** [ladyd252/Corky#4]
I might actually keep events and posts in a separate phase. Mainly because events is presumably going to be mostly done with rails/backbone whereas posts might include more twillio api stuff

**Comment by w1zeman1p** [comment]
Wait. Maybe it is broken up, but some of the models/controllers are referenced in phase 1?

**Comment by ladyd252** [comment]
Yes so I essentially counted the API for the posts as part of phase 1, but planning on doing the backbone models/views/routes etc later on in separate phases. Hopefully this will break it up enough.
